# Generated by Django 6.0.5 on 2026-05-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='admin_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='rejected_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ROLLBACK', 'Rollback — Needs Correction')], default='PENDING', max_length=20, null=True),
        ),
    ]
