# Generated by Django 5.2.4 on 2026-05-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyprofile_admin_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_status',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ROLLBACK', 'Rollback — Needs Correction')], default='PENDING', max_length=20, null=True),
        ),
    ]
