# Generated by Django 5.2.4 on 2026-05-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_company_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('CANDIDATE', 'Candidate'), ('ADMIN', 'admin')], default='CANDIDATE', max_length=20),
        ),
    ]
