# Generated by Django 6.0.5 on 2026-05-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='admin_message',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='rejected_fields',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ROLLBACK', 'Rollback — Needs Correction')], default='PENDING', max_length=20),
        ),
    ]
