# Generated by Django 6.0.5 on 2026-05-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_companyprofile_admin_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_name',
        ),
    ]
