# Generated by Django 6.0.5 on 2026-05-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_companyprofile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
