# Generated by Django 6.0.5 on 2026-05-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_companyprofile_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ROLLBACK', 'Rollback — Needs Correction')], default='PENDING', max_length=20, null=True),
        ),
    ]
