# Generated by Django 6.0.5 on 2026-05-24 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_companyprofile_company_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade_name', models.BooleanField(default=False)),
                ('legal_name', models.BooleanField(default=False)),
                ('ntn_number', models.BooleanField(default=False)),
                ('company_email', models.BooleanField(default=False)),
                ('company_type', models.BooleanField(default=False)),
                ('industry', models.BooleanField(default=False)),
                ('website', models.BooleanField(default=False)),
                ('country', models.BooleanField(default=False)),
                ('province', models.BooleanField(default=False)),
                ('city', models.BooleanField(default=False)),
                ('legal_address', models.BooleanField(default=False)),
                ('overview', models.BooleanField(default=False)),
                ('first_name', models.BooleanField(default=False)),
                ('last_name', models.BooleanField(default=False)),
                ('phone', models.BooleanField(default=False)),
                ('logo', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='accounts.companyprofile')),
            ],
        ),
    ]
