# Generated by Django 6.0.5 on 2026-05-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_companyrejection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyrejection',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='companyrejection',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='companyrejection',
            name='phone',
        ),
    ]
