"""
Django settings for JobHive project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys

from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


load_dotenv(BASE_DIR / ".env")


def env(name, default=""):
    return os.getenv(name, default).strip()

AUTH_USER_MODEL = "accounts.CustomUser"

# Payment gateway configuration. Keep credentials in the environment, never in source.
PAYMENT_MODE = env("PAYMENT_MODE", "sandbox").lower()
if PAYMENT_MODE not in {"sandbox", "production"}:
    PAYMENT_MODE = "sandbox"

PAYMENT_GATEWAY_TIMEOUT = int(env("PAYMENT_GATEWAY_TIMEOUT", "10"))
PAYMENT_CALLBACK_PATH = env("PAYMENT_CALLBACK_PATH", "/billing/payment/callback/")
PAYMENT_GATEWAYS = {
    "JazzCash": {
        "merchant_id": env("JAZZCASH_MERCHANT_ID"),
        "password": env("JAZZCASH_PASSWORD"),
        "integrity_salt": env("JAZZCASH_INTEGRITY_SALT"),
        "store_id": env("JAZZCASH_STORE_ID"),
        "sandbox_url": env(
            "JAZZCASH_SANDBOX_URL",
            "https://sandbox.jazzcash.com.pk/ApplicationAPI/API/Payment/DoTransaction",
        ),
        "production_url": env(
            "JAZZCASH_PRODUCTION_URL",
            "https://payments.jazzcash.com.pk/ApplicationAPI/API/Payment/DoTransaction",
        ),
    },
    "EasyPaisa": {
        "merchant_id": env("EASYPAISA_MERCHANT_ID"),
        "password": env("EASYPAISA_PASSWORD"),
        "integrity_salt": env("EASYPAISA_INTEGRITY_SALT"),
        "store_id": env("EASYPAISA_STORE_ID"),
        "sandbox_url": env("EASYPAISA_SANDBOX_URL"),
        "production_url": env("EASYPAISA_PRODUCTION_URL"),
    },
}


EMAIL_BACKEND = env("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(env("EMAIL_PORT", "587"))
EMAIL_USE_TLS = env("EMAIL_USE_TLS", "True").lower() in {"1", "true", "yes", "on"}
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-f5=-ork#!_z#(1#emdkv4&g%u5#+f+u7_o5203^(ys641*ce95"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['jobhive.pythonanywhere.com', 'localhost', '127.0.0.1']


# Application definition
sys.path.append(os.path.join(BASE_DIR, "apps"))
# Add the apps folder path
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.sites',

    # custom apps
    "accounts",
    "portal",
    "custom_admin",
    'candidate',
    'company',
    'job',
    'applications',
    'notifications',
    'billing',
    'chat',

    #All-Auth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "billing.middleware.CreditResetMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  #standard login
    "allauth.account.auth_backends.AuthenticationBackend",  #Google login
]

#All Auth Settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = "email"  # Google uses email
ACCOUNT_EMAIL_VERIFICATION = "none"  # Google already verified with email
LOGIN_REDIRECT_URL = "candidate_dashboard"  # Redirect after login
LOGOUT_REDIRECT_URL            = "login"



ROOT_URLCONF = "JobHive.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'notifications.context_processors.notification_context',
                'job.context_processors.global_job_categories',
                'chat.context_processors.unread_messages_count',
            ],
        },
    },
]

WSGI_APPLICATION = "JobHive.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "jobhive_db",  # database name
        "USER": "postgres",
        "PASSWORD": "root",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGIN_URL = 'login'  

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SOCIALACCOUNT_ADAPTER = "accounts.adapters.CustomSocialAccountAdapter"
ACCOUNT_ADAPTER = "accounts.account_adapter.CustomAccountAdapter"
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}
SOCIALACCOUNT_AUTO_SIGNUP = True
GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = env("GOOGLE_CLIENT_SECRET")


SITE_ID = 1