# Generated by Django 6.0.5 on 2026-07-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymentlog_account_number_paymentlog_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycredit',
            old_name='available_credits',
            new_name='addon_credits',
        ),
        migrations.AddField(
            model_name='companycredit',
            name='reset_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companycredit',
            name='subscription_credits',
            field=models.IntegerField(default=0),
        ),
    ]
