# Generated by Django 6.1 on 2026-08-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_resume_parsed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='has_experience',
            field=models.BooleanField(default=False),
        ),
    ]
