# Generated by Django 6.1 on 2026-08-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_remove_workexperience_has_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='has_experience',
            field=models.BooleanField(default=False),
        ),
    ]
