# Generated by Django 6.1 on 2026-08-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_workexperience_has_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='has_experience',
        ),
    ]
