# Generated by Django 6.1 on 2026-08-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_remove_workexperience_has_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='generated_resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resumes/generated/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_pdf_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
