# Generated by Django 6.0.5 on 2026-06-19 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_remove_companyrejection_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('experience_level', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('work_mode', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('vacancies', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('qualifications', models.TextField()),
                ('minimum_education', models.CharField(blank=True, max_length=100)),
                ('years_of_experience', models.CharField(blank=True, max_length=50)),
                ('skills', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('salary_type', models.CharField(choices=[('range', 'Salary Range'), ('fixed', 'Fixed Amount'), ('negotiable', 'Negotiable'), ('unpaid', 'Unpaid')], default='range', max_length=50)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('perks', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('PUBLISHED', 'Published'), ('DRAFT', 'Draft'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.companyprofile')),
            ],
            options={
                'verbose_name': 'Job Post',
                'verbose_name_plural': 'Job Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
