# Generated by Django 5.2.4 on 2026-06-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='PUBLISHED', max_length=20),
        ),
    ]
