# Generated by Django 6.0.5 on 2026-05-24 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'system'), ('CHAT', 'Chat'), ('APPLIED', 'Job-Applied'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('COMPANY', 'Company'), ('JOB', 'Job'), ('KYC_SUBMITTED', 'KYC_Submitted'), ('KYC_APPROVED', 'KYC_Approved'), ('KYC_REJECTED', 'KYC_Rejected'), ('KYC_ROLLBACK', 'KYC_Rollback'), ('NEW_APPLICATION', 'New-Application'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview_Scheduled'), ('INTERVIEW_RESCHEDULED', 'Interview_Rescheduled'), ('INTERVIEW_COMPLETED', 'Interview_Completed'), ('OFFER_CREATED', 'Offer_Created'), ('OFFER_ACCEPTED', 'Offer_Accepted'), ('OFFER_REJECTED', 'Offer_Rejected'), ('OFFER_EXPIRED', 'Offer_Expired'), ('OFFER_WITHDRAWN', 'Offer_Withdrawn'), ('JOB_CREATED', 'Job_Created'), ('JOB_UPDATE', 'Job_Updated'), ('JOB_DELETED', 'Job_Deleted'), ('JOB_PUBLISHED', 'Job_Published'), ('JOB_CLOSED', 'Job_Closed'), ('JOB_EXPIRED', 'Job_Expired'), ('JOB_FEATURED', 'Job_Featured'), ('JOB_UNFEATURED', 'Job_Unfeatured'), ('JOB_APPLIED', 'Job_Applied'), ('JOB_SHORTLISTED', 'Job_Shortlisted'), ('JOB_INTERVIEW_SCHEDULED', 'Job_Interview_Scheduled'), ('JOB_INTERVIEW_RESCHEDULED', 'Job_Interview_Rescheduled'), ('JOB_INTERVIEW_COMPLETED', 'Job_Interview_Completed'), ('JOB_OFFER_CREATED', 'Job_offer_Created'), ('JOB_OFFER_ACCEPTED', 'Job_offer_Accepted'), ('JOB_OFFER_REJECTED', 'Job_Offer_Rejected'), ('JOB_OFFER_EXPIRED', 'Job_Offer_Expired'), ('JOB_OFFER_WITHDRAWN', 'Job_Offer_Withdrawn'), ('ACCOUNT_ACTIVATED', 'Account_Activated'), ('ACCOUNT_DEACTIVATED', 'Account_Deactivated'), ('ACCOUNT_BANNED', 'Account_Banned'), ('ACCOUNT_UNBANNED', 'Account_Unbanned')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
