# Generated by Django 6.0.5 on 2026-07-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
